"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tokenizer.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'packages': [
        'wx', 'PyPDF2', 'tiktoken', 'requests'
    ],
    'includes': [
        'wx', 'os', 'PyPDF2', 'tiktoken', 're', 
        'altgraph', 'certifi', 'charset_normalizer', 'idna',
        'macholib', 'modulegraph', 'packaging', 'pillow', 
        'regex', 'requests', 'setuptools', 'six', 'urllib3'
    ],
    'plist': {
        'CFBundleName': 'Tokenizer',
        'CFBundleShortVersionString': '0.1',
        'CFBundleVersion': '0.1',
        'CFBundleIdentifier': 'br.com.andalik.clipboardtranslator',
        'NSHumanReadableCopyright': '© 2024 Andalik Industries',
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'CFBundleDocumentTypes': [{'CFBundleTypeName': 'MyFile','CFBundleTypeExtensions': ['*'],'CFBundleTypeRole': "Viewer"}],
        'LSEnvironment': {'LANG': 'en_US.UTF-8', 'LC_ALL': 'en_US.UTF-8'},
    },
    'iconfile': 'tokenizer.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)